tic
aux =string(fileread('input.txt'));
aux= regexprep(aux, '[\r\n]{2}', '\0$');
aux = regexprep(aux, '[\r\n]', ' ');

aux = num2cell(split(aux, '$'));
% aux = cellfun(@(x) replace(x, '\n', ' '), aux, 'UniformOutput', false);

key = {'ecl:(amb|blu|brn|gry|grn|hzl|oth)\W';'pid:[0-9]{9}\W';'eyr:((202[0-9])|(2030))\W';...
    'hcl:#[a-f0-9]{6}\W';'byr:((19[2-9][0-9])|(200[0-2]))\W';...
    'iyr:((201[0-9])|(2020))\W';'hgt:((1[5-8][0-9]|19[0-3])cm|(59|6[0-9]|7[0-6])in)\W'};

res = sum(cellfun(@(x) ~any([isempty(regexp(x,key{1},'ONCE')),...
    isempty(regexp(x,key{2},'ONCE')),...
    isempty(regexp(x,key{3},'ONCE')),...
    isempty(regexp(x,key{4},'ONCE')),...
    isempty(regexp(x,key{5},'ONCE')),...
    isempty(regexp(x,key{6},'ONCE')),...
    isempty(regexp(x,key{7},'ONCE'))]),...
    aux))
toc
